ImagesBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.ImagesBucket.name}
    CorsConfiguration:
      CorsRules:
        - AllowedOrigins:
            - '*'
          AllowedHeaders:
            - '*'
          AllowedMethods:
            - GET
            - PUT
            - POST
            - DELETE
            - HEAD
          MaxAge: 3000
          

ImagesBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref ImagesBucket
    PolicyDocument:
      Statement:
        Sid: PublicRead
        Effect: Allow
        Principal: '*'
        Action:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:DeleteObject
        Resource: arn:aws:s3:::${self:custom.ImagesBucket.name}/*
