# TAGS TABLE
TagsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: StarterTagsTable-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: name
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: name
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    Tags:
      - Key: name
        Value: starter-tags-table
